name: Deploy Frontend to HostGator

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Instalar dependências
      run: npm install --force

    - name: Build do frontend
      run: npm run build

    - name: Deploy via SCP (SFTP)
      uses: appleboy/scp-action@v0.1.4
      with:
        host: 162.240.159.68
        username: root
        password: ${{ secrets.DEPLOY_PASS }}
        port: 22022
        target: "/home/adminassociacaoa/public_html"
        source: "dist/*"
        strip_components: 1
        script: rm -rf /home/adminassociacaoa/public_html/assets/*
